---
name: heimdall
before:
  - 'export SECRET_KEY_BASE=xxx'
after_install: 'setup-secrets.sh'
build_dependencies:
  - ImageMagick-devel
  - libxml2-devel
  - libxslt-devel
  - openssl-devel
  - gcc
  - make
  - automake
dependencies:
  - openssl-libs
  - postgresql-server
  - ImageMagick
targets:
  centos-7:
