version: '3'

services:
  # If you wish to use a db other than mongo, this is 100% wrong
  db:
    build: "./dockerfiles/database"
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
      - "28017"
  web:
    build:
      context: ./
      dockerfile: ./dockerfiles/heimdall/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "db"

volumes:
  mongo_data:
